// <auto-generated />
using System;
using AssetManagmentApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AssetManagmentApp.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260813213329_AgregarCodigosRequisaYAlquiler")]
    partial class AgregarCodigosRequisaYAlquiler
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AssetManagmentApp.Models.Activo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Eliminado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("FechaRegistro")
                        .HasColumnType("date");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int?>("ProyectoActualId")
                        .HasColumnType("int");

                    b.Property<int>("TipoEquipoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Placa")
                        .IsUnique();

                    b.HasIndex("ProyectoActualId");

                    b.HasIndex("TipoEquipoId");

                    b.ToTable("Activos");
                });

            modelBuilder.Entity("AssetManagmentApp.Models.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("AssetManagmentApp.Models.AsignacionActivoProyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivoId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FechaIngreso")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaSalida")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaUltimoCobro")
                        .HasColumnType("date");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActivoId");

                    b.HasIndex("ProyectoId");

                    b.ToTable("AsignacionesActivoProyecto");
                });

            modelBuilder.Entity("AssetManagmentApp.Models.HistorialPrecioTipoEquipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("TipoEquipoId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("VigenteDesde")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("VigenteHasta")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("TipoEquipoId");

                    b.ToTable("HistorialPreciosTipoEquipo");
                });

            modelBuilder.Entity("AssetManagmentApp.Models.Movimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivoId")
                        .HasColumnType("int");

                    b.Property<string>("EstadoAnterior")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EstadoNuevo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaMovimiento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Observacion")
                        .HasColumnType("longtext");

                    b.Property<int?>("ProyectoId")
                        .HasColumnType("int");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActivoId");

                    b.HasIndex("ProyectoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Movimientos");
                });

            modelBuilder.Entity("AssetManagmentApp.Models.Proforma", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("EnviadaPorCorreo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("FechaGeneracion")
                        .HasColumnType("date");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateOnly>("PeriodoDesde")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PeriodoHasta")
                        .HasColumnType("date");

                    b.Property<int>("ProyectoId")
                        .HasColumnType("int");

                    b.Property<decimal?>("TipoCambio")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("UsuarioGeneroId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.HasIndex("ProyectoId");

                    b.HasIndex("UsuarioGeneroId");

                    b.ToTable("Proformas");
                });

            modelBuilder.Entity("AssetManagmentApp.Models.ProformaDetalle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActivoId")
                        .HasColumnType("int");

                    b.Property<string>("CodigoAlquiler")
                        .HasColumnType("longtext");

                    b.Property<int>("DiasCobrados")
                        .HasColumnType("int");

                    b.Property<decimal>("PrecioPorDiaUsado")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("ProformaId")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("TipoEquipoNombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ActivoId");

                    b.HasIndex("ProformaId");

                    b.ToTable("ProformaDetalles");
                });

            modelBuilder.Entity("AssetManagmentApp.Models.Proyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Actividad")
                        .HasColumnType("int");

                    b.Property<int?>("CodigoProyecto")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("FechaCreacion")
                        .HasColumnType("date");

                    b.Property<string>("IngenieroACargo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("Modelo")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("Obra")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("AssetManagmentApp.Models.SolicitudCorreccionAsignacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AsignacionActivoProyectoId")
                        .HasColumnType("int");

                    b.Property<string>("ComentarioResolucion")
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("FechaIngresoNueva")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaIngresoOriginal")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ProyectoNuevoId")
                        .HasColumnType("int");

                    b.Property<int>("ProyectoOriginalId")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioResuelveId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioSolicitaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AsignacionActivoProyectoId");

                    b.HasIndex("ProyectoNuevoId");

                    b.HasIndex("ProyectoOriginalId");

                    b.HasIndex("UsuarioResuelveId");

                    b.HasIndex("UsuarioSolicitaId");

                    b.ToTable("SolicitudesCorreccion");
                });

            modelBuilder.Entity("AssetManagmentApp.Models.TipoEquipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoAlquiler")
                        .HasColumnType("longtext");

                    b.Property<string>("Descripcion")
                        .HasColumnType("longtext");

                    b.Property<bool>("Eliminado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("PrecioPorDia")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("TiposEquipo");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AssetManagmentApp.Models.Activo", b =>
                {
                    b.HasOne("AssetManagmentApp.Models.Proyecto", "ProyectoActual")
                        .WithMany("ActivosAsignados")
                        .HasForeignKey("ProyectoActualId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("AssetManagmentApp.Models.TipoEquipo", "TipoEquipo")
                        .WithMany("Activos")
                        .HasForeignKey("TipoEquipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProyectoActual");

                    b.Navigation("TipoEquipo");
                });

            modelBuilder.Entity("AssetManagmentApp.Models.AsignacionActivoProyecto", b =>
                {
                    b.HasOne("AssetManagmentApp.Models.Activo", "Activo")
                        .WithMany("Asignaciones")
                        .HasForeignKey("ActivoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AssetManagmentApp.Models.Proyecto", "Proyecto")
                        .WithMany("Asignaciones")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Activo");

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("AssetManagmentApp.Models.HistorialPrecioTipoEquipo", b =>
                {
                    b.HasOne("AssetManagmentApp.Models.TipoEquipo", "TipoEquipo")
                        .WithMany("HistorialPrecios")
                        .HasForeignKey("TipoEquipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TipoEquipo");
                });

            modelBuilder.Entity("AssetManagmentApp.Models.Movimiento", b =>
                {
                    b.HasOne("AssetManagmentApp.Models.Activo", "Activo")
                        .WithMany("Movimientos")
                        .HasForeignKey("ActivoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AssetManagmentApp.Models.Proyecto", "Proyecto")
                        .WithMany("Movimientos")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AssetManagmentApp.Models.ApplicationUser", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Activo");

                    b.Navigation("Proyecto");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AssetManagmentApp.Models.Proforma", b =>
                {
                    b.HasOne("AssetManagmentApp.Models.Proyecto", "Proyecto")
                        .WithMany("Proformas")
                        .HasForeignKey("ProyectoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AssetManagmentApp.Models.ApplicationUser", "UsuarioGenero")
                        .WithMany()
                        .HasForeignKey("UsuarioGeneroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Proyecto");

                    b.Navigation("UsuarioGenero");
                });

            modelBuilder.Entity("AssetManagmentApp.Models.ProformaDetalle", b =>
                {
                    b.HasOne("AssetManagmentApp.Models.Activo", "Activo")
                        .WithMany("DetallesProforma")
                        .HasForeignKey("ActivoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AssetManagmentApp.Models.Proforma", "Proforma")
                        .WithMany("Detalles")
                        .HasForeignKey("ProformaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activo");

                    b.Navigation("Proforma");
                });

            modelBuilder.Entity("AssetManagmentApp.Models.SolicitudCorreccionAsignacion", b =>
                {
                    b.HasOne("AssetManagmentApp.Models.AsignacionActivoProyecto", "Asignacion")
                        .WithMany()
                        .HasForeignKey("AsignacionActivoProyectoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AssetManagmentApp.Models.Proyecto", "ProyectoNuevo")
                        .WithMany()
                        .HasForeignKey("ProyectoNuevoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AssetManagmentApp.Models.Proyecto", "ProyectoOriginal")
                        .WithMany()
                        .HasForeignKey("ProyectoOriginalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AssetManagmentApp.Models.ApplicationUser", "UsuarioResuelve")
                        .WithMany()
                        .HasForeignKey("UsuarioResuelveId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AssetManagmentApp.Models.ApplicationUser", "UsuarioSolicita")
                        .WithMany()
                        .HasForeignKey("UsuarioSolicitaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Asignacion");

                    b.Navigation("ProyectoNuevo");

                    b.Navigation("ProyectoOriginal");

                    b.Navigation("UsuarioResuelve");

                    b.Navigation("UsuarioSolicita");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("AssetManagmentApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("AssetManagmentApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AssetManagmentApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("AssetManagmentApp.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AssetManagmentApp.Models.Activo", b =>
                {
                    b.Navigation("Asignaciones");

                    b.Navigation("DetallesProforma");

                    b.Navigation("Movimientos");
                });

            modelBuilder.Entity("AssetManagmentApp.Models.Proforma", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("AssetManagmentApp.Models.Proyecto", b =>
                {
                    b.Navigation("ActivosAsignados");

                    b.Navigation("Asignaciones");

                    b.Navigation("Movimientos");

                    b.Navigation("Proformas");
                });

            modelBuilder.Entity("AssetManagmentApp.Models.TipoEquipo", b =>
                {
                    b.Navigation("Activos");

                    b.Navigation("HistorialPrecios");
                });
#pragma warning restore 612, 618
        }
    }
}
